### ISSUE TITLE
Markbot is not saying website is online

### ISSUE THREAD

**Issue by Pinestorm** [Pinestorm/html-validation-fixes#1]
As the title says. All commits were pushed and the index.html file is named correctly. However, when clicking the link it provides, https://pinestorm.github.io/html-validation-fixes/ , it shows the website. 
Apparently this was part of a glitch that a Markbot update caused?

@thomasjbradley

**Comment by thomasjbradley** [comment]
No, that one isn't part of the glitch. When did you last check in Markbot?

**Comment by Pinestorm** [comment]
Last I checked was Thursday morning in the lab, but I checked again now and It's working fine. That was a bit weird how it didn't show up before when I didn't change anything though.

**Comment by thomasjbradley** [comment]
Recently I've noticed that maybe the check is being cached or GitHub is throttling us or something—because the responses have been showing offline more than they should. I'm looking into the problem.
